version: '3'
services:
  sharedredis:
    image: redis:6.2.5-alpine
    ports:
      - 9230:6379
    networks:
      - birb

  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - birb

networks:
    birb:
      external: true
      name: birb